mines:
  mine1:
    enter_message: "Welcome to Mine 1!"
    leave_message: "You have left Mine 1."
    blocks:
      COAL_ORE:
        chance: 0.3
        drops:
          COAL:
            chance: 1.0
          IRON_INGOT:
            chance: 0.1
        sound_effect: false
      IRON_ORE:
        chance: 0.2
        drops:
          IRON_INGOT:
            chance: 1.0
        sound_effect: false
      DIAMOND_ORE:
        chance: 0.1
        drops:
          DIAMOND:
            chance: 1.0
        sound_effect: true
      STONE:
        chance: 0.4
        drops:
          COBBLESTONE:
            chance: 1.0
        sound_effect: false
    regeneration:
      min_time: 30
      max_time: 60
